FROM python:3.11-slim AS bot


ENV TELEGRAM_TOKEN ${6465163329:AAETwaKyIGdDGdm4lO_tPdYxA3VDANOAJkQ}


RUN pip3 install -r requirements.txt


CMD /Users/eldoratoyev/Desktop/Python/Imtixon/5-modul/bot.py;