version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${6465163329:AAETwaKyIGdDGdm4lO_tPdYxA3VDANOAJkQ}
    volumes:
      - "/storage:/storage"
    restart: always
